---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/kailan74/public_html/
    - /bin/rm -rf $DEPLOYPATH/assets
    - /bin/rm -rf $DEPLOYPATH/css
    - /bin/rm -rf $DEPLOYPATH/js
    - /bin/rm -f $DEPLOYPATH/index.html
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH